In [3]:
import pandas as pd

In [4]:
# 여러분의 폴더가 저장되어있는 위치 경로를 써 주세요
# 그리고 데이터파일(주최측에서 제공한) 의 이름을 Train set 으로 변셩해 주세요
# 한인욱 directory = 'C:/Users/goran/Desktop/Git_Hub/Project/20S_Bigcon'
# 김정현 directory = 'C:/Users/Coby/Desktop/20S_Bigcon/20S_Bigcon'
# 신예진 directory = 'C:/Users/Rstudio/Desktop/Bigcon2020/20S_Bigcon'
# 이규민 directory = 'C:/Statistics/20S_Bigcon'
# 최정욱 directory = 'C:/Users/lg/Desktop/Bigcon2020'
directory = 'C:/Users/goran/Desktop/Git_Hub/Project/20S_Bigcon/Analysis'

In [5]:
X_df=pd.read_excel(directory+'/X0819.xlsx')

In [7]:
X = X_df.copy() ; X

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,평균방송분,...,상품군power,CPI,CSI,RS,PrimeTime,남성상품,여성상품,무이자,일시불,유명기업/브랜드
0,0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,10.0,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
1,1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,10.0,...,26.41,0.8,97.5,139.3,0,0,1,0,0,0
2,2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,10.0,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
3,3,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,10.0,...,26.41,0.8,97.5,139.3,0,0,1,0,0,0
4,4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,10.0,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,35374,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,5.0,...,19.40,0.7,100.5,138.0,0,0,0,0,1,1
35375,35375,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,1,0,1
35376,35376,2020-01-01 00:00:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,0,1,1
35377,35377,2020-01-01 00:00:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,1,0,1
35378,35378,2020-01-01 00:00:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,0,1,1

In [8]:
X.drop(columns=['Unnamed: 0'],inplace=True)

In [9]:
# target data
y=X['취급액']

In [156]:
# X_train data
X.drop(columns = ['취급액'],inplace=True)

In [157]:
X.drop(columns = ['방송일시','마더코드','상품코드','상품명','요일/시간','년','월','일','시분','날짜'],inplace = True)

In [158]:
X.columns

Index(['노출(분)', '상품군', '판매단가', '평균방송분', '겹치는수', '시각', '점심', '저녁', '강수량(mm)',
       '평균기온(℃)', '최저기온(℃)', '최고기온(℃)', '연예인', '월급날', '휴일', '상품군power', 'CPI',
       'CSI', 'RS', '20분당당일평균시청률', '일평균시청률', '20분당일년평균시청률', 'PrimeTime',
       '남성상품', '여성상품', '무이자', '일시불', '유명기업/브랜드'],
      dtype='object')

# 더미화

In [159]:
X

,노출(분),상품군,판매단가,평균방송분,겹치는수,시각,점심,저녁,강수량(mm),평균기온(℃),...,RS,20분당당일평균시청률,일평균시청률,20분당일년평균시청률,PrimeTime,남성상품,여성상품,무이자,일시불,유명기업/브랜드
0,20.0,의류,39900,10.0,1,6.000000,0,0,0.1,-2.1,...,139.3,0.001309,0.004,0.00215,0,1,0,0,0,0
1,20.0,의류,39900,10.0,1,6.000000,0,0,0.1,-2.1,...,139.3,0.001309,0.004,0.00215,0,0,1,0,0,0
2,20.0,의류,39900,10.0,2,6.333333,0,0,0.1,-2.1,...,139.3,0.001012,0.004,0.00200,0,1,0,0,0,0
3,20.0,의류,39900,10.0,2,6.333333,0,0,0.1,-2.1,...,139.3,0.001012,0.004,0.00200,0,0,1,0,0,0
4,20.0,의류,39900,10.0,3,6.666667,0,0,0.1,-2.1,...,139.3,0.002180,0.004,0.00225,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,20.0,주방,148000,5.0,2,23.666666,0,0,0.1,-3.8,...,138.0,0.020648,0.005,0.00460,0,0,0,0,1,1
37368,20.0,주방,178000,5.0,3,24.000000,0,0,0.0,4.1,...,131.7,0.026600,0.000,0.00460,0,0,0,1,0,1
37369,20.0,주방,168000,5.0,3,24.000000,0,0,0.0,4.1,...,131.7,0.026600,0.000,0.00460,0,0,0,0,1,1
37370,20.0,주방,158000,5.0,3,24.000000,0,0,0.0,4.1,...,131.7,0.026600,0.000,0.00460,0,0,0,1,0,1
37371,20.0,주방,148000,5.0,3,24.000000,0,0,0.0,4.1,...,131.7,0.026600,0.000,0.00460,0,0,0,0,1,1

In [160]:
col=['노출(분)', '판매단가','평균방송분','시각','강수량','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS',
 '20분당당일평균시청률', '일평균시청률', '20분당일년평균시청률']

In [161]:
df = X.copy()

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37372 entries, 0 to 37371
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   노출(분)        37372 non-null  float64
 1   상품군          37372 non-null  object
 2   판매단가         37372 non-null  int64
 3   평균방송분        37372 non-null  float64
 4   겹치는수         37372 non-null  int64
 5   시각           37372 non-null  float64
 6   점심           37372 non-null  int64
 7   저녁           37372 non-null  int64
 8   강수량(mm)      37372 non-null  float64
 9   평균기온(℃)      37372 non-null  float64
 10  최저기온(℃)      37372 non-null  float64
 11  최고기온(℃)      37372 non-null  float64
 12  연예인          37372 non-null  int64
 13  월급날          37372 non-null  int64
 14  휴일           37372 non-null  int64
 15  상품군power     37372 non-null  float64
 16  CPI          37372 non-null  float64
 17  CSI          37372 non-null  float64
 18  RS           37372 non-null  float64
 19  20분당당일평균시청률  37372 non-null  float64
 20  일평균시청률       37372 non-null  float64
 21  20분당일년평균시청률  37372 non-null  float64
 22  PrimeTime    37372 non-null  int64
 23  남성상품         37372 non-null  int64
 24  여성상품         37372 non-null  int64
 25  무이자          37372 non-null  int64
 26  일시불          37372 non-null  int64
 27  유명기업/브랜드     37372 non-null  int64
dtypes: float64(14), int64(13), object(1)
memory usage: 8.0+ MB

In [163]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [164]:
k=scaler.fit_transform(X.loc[:,['노출(분)','판매단가','평균방송분','겹치는수','시각','강수량(mm)','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS',
 '20분당당일평균시청률', '일평균시청률', '20분당일년평균시청률']])

In [165]:
p=pd.DataFrame(k,columns=['노출(분)','판매단가','평균방송분','겹치는수','시각','강수량(mm)','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS',
 '20분당당일평균시청률', '일평균시청률', '20분당일년평균시청률'])

In [166]:
X.loc[:,['노출(분)','판매단가','평균방송분','겹치는수','시각','강수량(mm)','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS',
 '20분당당일평균시청률', '일평균시청률', '20분당일년평균시청률']] = p

In [167]:
X

,노출(분),상품군,판매단가,평균방송분,겹치는수,시각,점심,저녁,강수량(mm),평균기온(℃),...,RS,20분당당일평균시청률,일평균시청률,20분당일년평균시청률,PrimeTime,남성상품,여성상품,무이자,일시불,유명기업/브랜드
0,-0.123014,의류,-0.585286,-0.148539,-1.127297,-1.857714,0,0,-0.349634,-1.771135,...,1.167920,-0.597583,-0.103654,-1.570236,0,1,0,0,0,0
1,-0.123014,의류,-0.585286,-0.148539,-1.127297,-1.857714,0,0,-0.349634,-1.771135,...,1.167920,-0.597583,-0.103654,-1.570236,0,0,1,0,0,0
2,-0.123014,의류,-0.585286,-0.148539,0.013029,-1.799534,0,0,-0.349634,-1.771135,...,1.167920,-0.620466,-0.103654,-1.673867,0,1,0,0,0,0
3,-0.123014,의류,-0.585286,-0.148539,0.013029,-1.799534,0,0,-0.349634,-1.771135,...,1.167920,-0.620466,-0.103654,-1.673867,0,0,1,0,0,0
4,-0.123014,의류,-0.585286,-0.148539,1.153355,-1.741354,0,0,-0.349634,-1.771135,...,1.167920,-0.530589,-0.103654,-1.501149,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,-0.123014,주방,-0.437495,-0.858250,0.013029,1.225840,0,0,-0.349634,-1.959789,...,1.006155,0.889896,0.330673,0.122400,0,0,0,0,1,1
37368,-0.123014,주방,-0.396480,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,...,0.222221,1.347700,-1.840964,0.122400,0,0,0,1,0,1
37369,-0.123014,주방,-0.410151,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,...,0.222221,1.347700,-1.840964,0.122400,0,0,0,0,1,1
37370,-0.123014,주방,-0.423823,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,...,0.222221,1.347700,-1.840964,0.122400,0,0,0,1,0,1
37371,-0.123014,주방,-0.437495,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,...,0.222221,1.347700,-1.840964,0.122400,0,0,0,0,1,1

In [168]:
X = pd.get_dummies(X,columns=['상품군'])

In [169]:
X

,노출(분),판매단가,평균방송분,겹치는수,시각,점심,저녁,강수량(mm),평균기온(℃),최저기온(℃),...,상품군_가전,상품군_건강기능,상품군_농수축,상품군_생활용품,상품군_속옷,상품군_의류,상품군_이미용,상품군_잡화,상품군_주방,상품군_침구
0,-0.123014,-0.585286,-0.148539,-1.127297,-1.857714,0,0,-0.349634,-1.771135,-1.542752,...,0,0,0,0,0,1,0,0,0,0
1,-0.123014,-0.585286,-0.148539,-1.127297,-1.857714,0,0,-0.349634,-1.771135,-1.542752,...,0,0,0,0,0,1,0,0,0,0
2,-0.123014,-0.585286,-0.148539,0.013029,-1.799534,0,0,-0.349634,-1.771135,-1.542752,...,0,0,0,0,0,1,0,0,0,0
3,-0.123014,-0.585286,-0.148539,0.013029,-1.799534,0,0,-0.349634,-1.771135,-1.542752,...,0,0,0,0,0,1,0,0,0,0
4,-0.123014,-0.585286,-0.148539,1.153355,-1.741354,0,0,-0.349634,-1.771135,-1.542752,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,-0.123014,-0.437495,-0.858250,0.013029,1.225840,0,0,-0.349634,-1.959789,-1.636764,...,0,0,0,0,0,0,0,0,1,0
37368,-0.123014,-0.396480,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,-1.615872,...,0,0,0,0,0,0,0,0,1,0
37369,-0.123014,-0.410151,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,-1.615872,...,0,0,0,0,0,0,0,0,1,0
37370,-0.123014,-0.423823,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,-1.615872,...,0,0,0,0,0,0,0,0,1,0
37371,-0.123014,-0.437495,-0.858250,1.153355,1.284021,0,0,-0.360164,-1.083103,-1.615872,...,0,0,0,0,0,0,0,0,1,0

In [148]:
X.to_excel('연습.xlsx')