In [1]:
import pandas as pd

In [2]:
# 여러분의 폴더가 저장되어있는 위치 경로를 써 주세요
# 그리고 데이터파일(주최측에서 제공한) 의 이름을 Train set 으로 변셩해 주세요
# 한인욱 directory = 'C:/Users/goran/Desktop/Git_Hub/Project/20S_Bigcon'
# 김정현 directory = 'C:/Users/Coby/Desktop/20S_Bigcon/20S_Bigcon'
# 신예진 directory = 'C:/Users/Rstudio/Desktop/Bigcon2020/20S_Bigcon'
# 이규민 directory = 'C:/Statistics/20S_Bigcon'
# 최정욱 directory = 'C:/Users/lg/Desktop/Bigcon2020'
directory = 'C:/Users/Rstudio/Desktop/Bigcon2020/20S_Bigcon'

In [3]:
X_df=pd.read_excel(directory+'/X0819.xlsx')

In [4]:
X = X_df.copy() ; X

,Unnamed: 0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액,평균방송분,...,상품군power,CPI,CSI,RS,PrimeTime,남성상품,여성상품,무이자,일시불,유명기업/브랜드
0,0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,10.0,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
1,1,2019-01-01 06:00:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,10.0,...,26.41,0.8,97.5,139.3,0,0,1,0,0,0
2,2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,10.0,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
3,3,2019-01-01 06:20:00,20.0,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,10.0,...,26.41,0.8,97.5,139.3,0,0,1,0,0,0
4,4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,10.0,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,35374,2019-12-31 23:40:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,5.0,...,19.40,0.7,100.5,138.0,0,0,0,0,1,1
35375,35375,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,1,0,1
35376,35376,2020-01-01 00:00:00,20.0,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,0,1,1
35377,35377,2020-01-01 00:00:00,20.0,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,1,0,1
35378,35378,2020-01-01 00:00:00,20.0,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,5.0,...,19.40,1.5,104.2,131.7,0,0,0,0,1,1

In [5]:
X.drop(columns=['Unnamed: 0'],inplace=True)

In [6]:
# target data
y=X['취급액']

In [7]:
# X_train data
X.drop(columns = ['취급액'],inplace=True)

In [8]:
X.drop(columns = ['방송일시','마더코드','상품코드','상품명','요일/시간','년','월','일','시분','월일','시간열','정수노출(분)','날짜'],inplace = True)

In [9]:
X.columns

Index(['노출(분)', '상품군', '판매단가', '평균방송분', '겹치는수', '시각', '시청률평균', '점심', '저녁',
       '강수량(mm)', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)', '연예인', '월급날', '휴일',
       '상품군power', 'CPI', 'CSI', 'RS', 'PrimeTime', '남성상품', '여성상품', '무이자',
       '일시불', '유명기업/브랜드'],
      dtype='object')

# 더미화

In [10]:
X

,노출(분),상품군,판매단가,평균방송분,겹치는수,시각,시청률평균,점심,저녁,강수량(mm),...,상품군power,CPI,CSI,RS,PrimeTime,남성상품,여성상품,무이자,일시불,유명기업/브랜드
0,20.0,의류,39900,10.0,1,6.000000,0.002632,0,0,0.1,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
1,20.0,의류,39900,10.0,1,6.000000,0.002632,0,0,0.1,...,26.41,0.8,97.5,139.3,0,0,1,0,0,0
2,20.0,의류,39900,10.0,2,6.333333,0.002434,0,0,0.1,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
3,20.0,의류,39900,10.0,2,6.333333,0.002434,0,0,0.1,...,26.41,0.8,97.5,139.3,0,0,1,0,0,0
4,20.0,의류,39900,10.0,3,6.666667,0.003162,0,0,0.1,...,26.41,0.8,97.5,139.3,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,20.0,주방,148000,5.0,2,23.666666,0.004741,0,0,0.1,...,19.40,0.7,100.5,138.0,0,0,0,0,1,1
35375,20.0,주방,178000,5.0,3,24.000000,0.004069,0,0,0.0,...,19.40,1.5,104.2,131.7,0,0,0,1,0,1
35376,20.0,주방,168000,5.0,3,24.000000,0.004069,0,0,0.0,...,19.40,1.5,104.2,131.7,0,0,0,0,1,1
35377,20.0,주방,158000,5.0,3,24.000000,0.004069,0,0,0.0,...,19.40,1.5,104.2,131.7,0,0,0,1,0,1
35378,20.0,주방,148000,5.0,3,24.000000,0.004069,0,0,0.0,...,19.40,1.5,104.2,131.7,0,0,0,0,1,1

In [11]:
col=['노출(분)', '판매단가','평균방송분','시각','시청률평균','강수량(mm)','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS']

In [12]:
df = X.copy()

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35379 entries, 0 to 35378
Data columns (total 26 columns):
노출(분)        35379 non-null float64
상품군          35379 non-null object
판매단가         35379 non-null int64
평균방송분        35379 non-null float64
겹치는수         35379 non-null int64
시각           35379 non-null float64
시청률평균        35379 non-null float64
점심           35379 non-null int64
저녁           35379 non-null int64
강수량(mm)      35379 non-null float64
평균기온(℃)      35379 non-null float64
최저기온(℃)      35379 non-null float64
최고기온(℃)      35379 non-null float64
연예인          35379 non-null int64
월급날          35379 non-null int64
휴일           35379 non-null int64
상품군power     35379 non-null float64
CPI          35379 non-null float64
CSI          35379 non-null float64
RS           35379 non-null float64
PrimeTime    35379 non-null int64
남성상품         35379 non-null int64
여성상품         35379 non-null int64
무이자          35379 non-null int64
일시불          35379 non-null int64
유명기업/브랜드     35379 non-null int64
dtypes: float64(12), int64(13), object(1)
memory usage: 7.0+ MB

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [16]:
k=scaler.fit_transform(X.loc[:,['노출(분)', '판매단가','평균방송분','시각','시청률평균','강수량(mm)','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS']])

In [17]:
p=pd.DataFrame(k,columns=['노출(분)', '판매단가','평균방송분','시각','시청률평균','강수량(mm)','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS'])

In [18]:
X.loc[:,['노출(분)', '판매단가','평균방송분','시각','시청률평균','강수량(mm)','평균기온(℃)',
 '최저기온(℃)', '최고기온(℃)' ,'상품군power', 'CPI','CSI', 'RS']] = p

In [19]:
X

,노출(분),상품군,판매단가,평균방송분,겹치는수,시각,시청률평균,점심,저녁,강수량(mm),...,상품군power,CPI,CSI,RS,PrimeTime,남성상품,여성상품,무이자,일시불,유명기업/브랜드
0,-0.109679,의류,-0.555490,-0.208581,1,-1.826372,-1.804510,0,0,-0.347927,...,0.273575,1.117307,-0.314122,1.156173,0,1,0,0,0,0
1,-0.109679,의류,-0.555490,-0.208581,1,-1.826372,-1.804510,0,0,-0.347927,...,0.273575,1.117307,-0.314122,1.156173,0,0,1,0,0,0
2,-0.109679,의류,-0.555490,-0.208581,2,-1.768220,-1.976626,0,0,-0.347927,...,0.273575,1.117307,-0.314122,1.156173,0,1,0,0,0,0
3,-0.109679,의류,-0.555490,-0.208581,2,-1.768220,-1.976626,0,0,-0.347927,...,0.273575,1.117307,-0.314122,1.156173,0,0,1,0,0,0
4,-0.109679,의류,-0.555490,-0.208581,3,-1.710068,-1.343825,0,0,-0.347927,...,0.273575,1.117307,-0.314122,1.156173,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,-0.109679,주방,-0.382917,-0.922281,2,1.255686,0.029393,0,0,-0.347927,...,-0.232653,0.836731,0.933380,0.994927,0,0,0,0,1,1
35375,-0.109679,주방,-0.335024,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,...,-0.232653,3.081337,2.471967,0.213502,0,0,0,1,0,1
35376,-0.109679,주방,-0.350988,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,...,-0.232653,3.081337,2.471967,0.213502,0,0,0,0,1,1
35377,-0.109679,주방,-0.366952,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,...,-0.232653,3.081337,2.471967,0.213502,0,0,0,1,0,1
35378,-0.109679,주방,-0.382917,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,...,-0.232653,3.081337,2.471967,0.213502,0,0,0,0,1,1

In [20]:
X = pd.get_dummies(X,columns=['상품군'])

In [21]:
X

,노출(분),판매단가,평균방송분,겹치는수,시각,시청률평균,점심,저녁,강수량(mm),평균기온(℃),...,상품군_가전,상품군_건강기능,상품군_농수축,상품군_생활용품,상품군_속옷,상품군_의류,상품군_이미용,상품군_잡화,상품군_주방,상품군_침구
0,-0.109679,-0.555490,-0.208581,1,-1.826372,-1.804510,0,0,-0.347927,-1.760509,...,0,0,0,0,0,1,0,0,0,0
1,-0.109679,-0.555490,-0.208581,1,-1.826372,-1.804510,0,0,-0.347927,-1.760509,...,0,0,0,0,0,1,0,0,0,0
2,-0.109679,-0.555490,-0.208581,2,-1.768220,-1.976626,0,0,-0.347927,-1.760509,...,0,0,0,0,0,1,0,0,0,0
3,-0.109679,-0.555490,-0.208581,2,-1.768220,-1.976626,0,0,-0.347927,-1.760509,...,0,0,0,0,0,1,0,0,0,0
4,-0.109679,-0.555490,-0.208581,3,-1.710068,-1.343825,0,0,-0.347927,-1.760509,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,-0.109679,-0.382917,-0.922281,2,1.255686,0.029393,0,0,-0.347927,-1.948998,...,0,0,0,0,0,0,0,0,1,0
35375,-0.109679,-0.335024,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,-1.073076,...,0,0,0,0,0,0,0,0,1,0
35376,-0.109679,-0.350988,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,-1.073076,...,0,0,0,0,0,0,0,0,1,0
35377,-0.109679,-0.366952,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,-1.073076,...,0,0,0,0,0,0,0,0,1,0
35378,-0.109679,-0.382917,-0.922281,3,1.313839,-0.554547,0,0,-0.358480,-1.073076,...,0,0,0,0,0,0,0,0,1,0

In [22]:
X.to_excel('연습.xlsx')